package csvtool.remap;

import java.util.List;

public class RemapExamples
{
	public static final List<String> EXAMPLE_LIST = List.of(
			"This file defines the --reformat functionality's behavior.",
			"It is organized by column index, and a list of 'CSVRemap' functions; which are listed below.",
			"There is also a 'remap_examples' to show how this configuration file can be used.",
			"The resulting output gets then remapped using the 'Input' Headers, being transformed to the 'Output' Headers.",
			"This process requires the correct number of DROP remaps to be performed so that the column count is equal to the output column size.",
			"--------------------------------------------------------------------------------------------------------------------------------------",
			"NONE (Performs no remap)",
			"DROP (Performs a Column Removal, and advances to the next)",
			"EMPTY (Performs a field empty which deletes any existing data)",
			"STATIC { (old), [new], ... } (Performs a static 1-to-1 swap if (old) exists, swap it with [new], or if only 1 parameter, set data to (old) regardless, and optionally an extended list)",
			"DATE { (old-fmt), (new-fmt) } (Performs a date reformat based on (old-fmt) into (new-fmt); this uses SimpleDateFormat patterns)",
			"DATE_NOW { (fmt) } (Performs a date format based on (fmt) of now; using SimpleDateFormat patterns)",
			"DATE_YEARS { (fmt) } (Performs a date format based on (fmt) of now; using SimpleDateFormat patterns, and then returns the duration in Years since.)",
			"DATE_MONTHS { (fmt) } (Performs a date format based on (fmt) of now; using SimpleDateFormat patterns, and then returns the duration in Months since.)",
			"DATE_DAYS { (fmt) } (Performs a date format based on (fmt) of now; using SimpleDateFormat patterns, and then returns the duration in Days since.)",
			"DATE_EPOCH { (fmt), [multiplier] } (Performs a date format based on (fmt) of an Epoch value (multiplied by an optional [multiplier], such as for converting seconds to millis); using DateTimeFormatter patterns, and then returns the time/date represented aligned to UTC)",
			"INCLUDE (...) (Performs a row exclusion if this field does not match items on a list)",
			"EXCLUDE (...) (Performs a row exclusion if this field matches items in a list)",
			"INCLUDE_REGEX (RegEx) (Performs a row exclusion if this field does not match the RegEx)",
			"EXCLUDE_REGEX (RegEx) (Performs a row exclusion if this field matches the RegEx)",
			"EXCLUDE_EMPTY (Performs a row exclusion if this field is empty)",
			"PAD { (count), [data] } (Pads this value with (count) and optional [data])",
			"TRUNCATE { (length) } (Truncates the value to a length of (length))",
			"TOKEN_TRUNCATE { (token), (length) } (Truncates the value to a length of (length), based on a (token) to split the values)",
			"IF_STATIC { (field-id), (condition), (value) } (Performs a value static if the value in (field-id) matches (condition), then this field becomes (value))",
			"IF_EMPTY { (value), [subRemap] } (Performs a value static if the value is empty, then this field becomes (value), or applies the optional [subRemap])",
			"IF_EMPTY_FIELD { (other-field), (value), [subRemap] } (Performs a value static if the value in (other-field) is empty, then this field becomes (value), or applies the optional [subRemap])",
			"IF_EMPTY_COPY { (other-field), [subRemap] } (Performs a value copy if the value is empty, or preserve the data and apply the optional [subRemap])",
			"IF_EQUAL { (field), (value-true), [value-false] } (Performs a field compare of (field), and if they match, return (value-true), or optionally [value-false])",
			"IF_EQUAL_COPY { (field1), (field2) } (Performs a field compare of (field1) with this data, and if they match, return value of (field2))",
			"IF_EQUAL_APPEND { (field), (value), [token] } (Performs a field compare of (field) with this data, and if they match, append the value of (value), with a space or [token] in between)",
			"IF_EQUAL_PREFIX { (field), (value), [token], [subRemap] } (Performs a value prefix if the value in (field) is equal, with the value in (value), with a space or [token] in between; or preserve the data and apply the optional [subRemap])",
			"IF_FIELDS_EQUAL { (field1), (field2), (value-true), (value-false) } (Performs a field compare of (field1) with (field2), and if they match, return (value-true), or (value-false))",
			"IF_RANGE { (min-value), (max-value), (result), [else], {...} }",
			"* (Performs an integer comparison of existing data using >= (min-value) and <= (max-value), then return (result), or return [else]; can be chained for multiple range tests)",
			"IF_DATE_RANGE { (data-fmt), (min-field), (min-fmt), (max-field), (max-fmt), (before), (between), (after), (out-of-range) } ",
			"* (Performs a date (data-fmt) comparison of existing data using (min-field) with (min-fmt) and <= (max-field) with (max-fmt), then return (before), (between), (after), or (out-of-range); using SimpleDateFormat patterns)",
			"IF_NUMBER_EMPTY (If value successfully parses into a number, empty the value)",
			"IF_FLOAT_EMPTY (If value successfully parses into a float, empty the value)",
			"NOT_EMPTY { (value), [subRemap] } (Performs a value static if the value is not empty, then this field becomes (value), or applies the optional [subRemap])",
			"NOT_EMPTY_FIELD { (other-field), (value), [subRemap] } (Performs a value static if the value in (other-field) is not empty, then this field becomes (value), or applies the optional [subRemap])",
			"NOT_EMPTY_APPEND { (other-field), (value), [token], [subRemap] } (Performs a (value) append if the value in (other-field) and this field is not empty, with a space or [token] in between; or preserve the data and apply the optional [subRemap])",
			"NOT_EMPTY_COPY { (other-field), [subRemap] } (Performs a value copy from (other-field) if the value is not empty, or preserve the data and apply the optional [subRemap])",
			"NOT_EMPTY_MERGE { (other-field), [token], [subRemap] } (Performs a value merge if the value in (other-field) is not empty, with a space or [token] in between; or preserve the data and apply the optional [subRemap])",
			"NOT_EMPTY_PREFIX { (value), [token], [subRemap] } (Performs a value prefix with the value in (value), with a space or [token] in between; or preserve the data and apply the optional [subRemap])",
			"NOT_NUMBER_EMPTY (If value fails to parse into a number, empty the value)",
			"NOT_FLOAT_EMPTY (If value fails to parse into a float, empty the value)",
			"PHONE_NUMBER { [format] } (Performs a phone Number Reformat using PhoneNumberUtil into the optional [format], such as 'RFC3966' (default), or 'E164')",
			"COPY { (field-id) } (Performs a value copy of the value in (field-id))",
			"MERGE { (field-id), [token] } (Performs a value merge from the value in (field-id), with a space or [token] in between)",
			"APPEND { (value), [token] } (Performs a value append of the value in (value), with a space or [token] in between)",
			"PREFIX { (value), [token] } (Performs a value prefix with the value in (value), with a space or [token] in between)",
			"REPLACE { (value), [token] } (Performs a value replace of the value in (value), with a space or [token] in between; if found)",
			"LEFT { (length) } (Performs a value left-facing trim by (length) characters)",
			"RIGHT { (length) } (Performs a value right-facing trim by (length) characters)",
			"SANITIZE { } (Performs a string sanitize to replace all unsafe characters)",
			"SWAP (field-id) + subRemap (Performs a field swap with field-id, and also copies the subRemap and executes it)",
			"* subRemap {}: (Any Remap except for a SWAP and DROP; can be nested with a subRemap type)"
	);

	public static final RemapList EXAMPLES = new RemapList(
			List.of(
					new CSVRemap(0, RemapType.NONE),
					new CSVRemap(1, RemapType.DROP),
					new CSVRemap(2, RemapType.EMPTY),
					new CSVRemap(3, RemapType.STATIC, List.of("apple", "orange")),
					new CSVRemap(4, RemapType.DATE, List.of("yyyyMMdd", "yyyy-MM-dd")),
					new CSVRemap(5, RemapType.DATE_NOW, List.of("yyyy-MM-dd")),
					new CSVRemap(6, RemapType.DATE_YEARS, List.of("yyyy-MM-dd")),
					new CSVRemap(7, RemapType.DATE_MONTHS, List.of("yyyy-MM-dd")),
					new CSVRemap(8, RemapType.DATE_DAYS, List.of("yyyy-MM-dd")),
					new CSVRemap(9, RemapType.DATE_EPOCH, List.of("yyyy-MM-dd HH:mm:ss")),
					new CSVRemap(10, RemapType.INCLUDE, List.of("01", "02", "03")),
					new CSVRemap(11, RemapType.EXCLUDE, List.of("04", "05", "06")),
					new CSVRemap(12, RemapType.INCLUDE_REGEX, List.of("(?:^|\\W)included(?:$|\\W)")),
					new CSVRemap(13, RemapType.EXCLUDE_REGEX, List.of("(?:^|\\W)excluded(?:$|\\W)")),
					new CSVRemap(14, RemapType.EXCLUDE_EMPTY, List.of()),
					new CSVRemap(15, RemapType.PAD, List.of("3", "0")),
					new CSVRemap(16, RemapType.TRUNCATE, List.of("1")),
					new CSVRemap(17, RemapType.TOKEN_TRUNCATE, List.of(",", "100")),
					new CSVRemap(18, RemapType.IF_STATIC, List.of("2", "apple", "orange")),
					new CSVRemap(19, RemapType.IF_EMPTY, List.of("was_empty")),
					new CSVRemap(20, RemapType.IF_EMPTY_FIELD, List.of("2", "its_empty")),
					new CSVRemap(21, RemapType.IF_EMPTY_COPY, List.of("3")),
					new CSVRemap(22, RemapType.IF_EQUAL, List.of("13", "equal", "not equal")),
					new CSVRemap(23, RemapType.IF_EQUAL_COPY, List.of("13", "14")),
					new CSVRemap(24, RemapType.IF_EQUAL_APPEND, List.of("13", "append")),
					new CSVRemap(25, RemapType.IF_EQUAL_PREFIX, List.of("13", "prefix", ":")),
					new CSVRemap(26, RemapType.IF_FIELDS_EQUAL, List.of("13", "14", "equal", "not equal")),
					new CSVRemap(27, RemapType.IF_RANGE, List.of("0", "15", "Less than 16", "16", "32", "Between 16 and 32", "Above 32")),
					new CSVRemap(28, RemapType.IF_DATE_RANGE, List.of("MM/dd/yyyy", "4", "MM/dd/yyyy", "5", "MM/dd/yyyy", "Before TimeDate", "During TimeDate", "After TimeDate", "Out of Range")),
					new CSVRemap(29, RemapType.IF_NUMBER_EMPTY, List.of()),
					new CSVRemap(30, RemapType.IF_FLOAT_EMPTY, List.of()),
					new CSVRemap(31, RemapType.NOT_EMPTY, List.of("not_empty")),
					new CSVRemap(32, RemapType.NOT_EMPTY_FIELD, List.of("2", "not_empty")),
					new CSVRemap(33, RemapType.NOT_EMPTY_APPEND, List.of("3", "\n")),
					new CSVRemap(34, RemapType.NOT_EMPTY_COPY, List.of("3")),
					new CSVRemap(35, RemapType.NOT_EMPTY_MERGE, List.of("4")),
					new CSVRemap(36, RemapType.NOT_EMPTY_PREFIX, List.of("PREFIX: ")),
					new CSVRemap(37, RemapType.NOT_NUMBER_EMPTY, List.of()),
					new CSVRemap(38, RemapType.NOT_FLOAT_EMPTY, List.of()),
					new CSVRemap(39, RemapType.COPY, List.of("3")),
					new CSVRemap(40, RemapType.MERGE, List.of("3")),
					new CSVRemap(41, RemapType.APPEND, List.of("Extra")),
					new CSVRemap(42, RemapType.PREFIX, List.of("PREFIX: ")),
					new CSVRemap(43, RemapType.REPLACE, List.of("DEL", "")),
					new CSVRemap(44, RemapType.LEFT, List.of("4")),
					new CSVRemap(45, RemapType.RIGHT, List.of("4")),
					new CSVRemap(46, RemapType.SANITIZE, List.of()),
					new CSVRemap(47, RemapType.PHONE_NUMBER, List.of("E164")),
					new CSVRemap(48, RemapType.SWAP, List.of("2"),
					             new CSVRemap(3, RemapType.STATIC, List.of("orange", "banana"))
					)
			       )
	);
}
